# Generated by Django 2.2.5 on 2019-09-25 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAluno', models.IntegerField()),
                ('nomeAluno', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDisciplina', models.IntegerField()),
                ('nomeDisciplina', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('presente', models.IntegerField()),
                ('data', models.CharField(max_length=100)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Aluno')),
                ('discliplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='AlunoDisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Aluno')),
                ('discliplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Disciplina')),
            ],
        ),
    ]
