# Generated by Django 2.2.5 on 2019-09-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_aluno_alunodisciplina_disciplina_frequencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='idAluno',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='idDisciplina',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alunodisciplina',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
