# Generated by Django 2.2.5 on 2019-09-25 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190925_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencia',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='data',
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='discliplina',
        ),
    ]
