# Generated by Django 2.2.5 on 2019-09-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190925_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='aluno_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='data',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='disciplina_id',
            field=models.IntegerField(default=0),
        ),
    ]
