# Generated by Django 2.2.5 on 2019-09-25 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190925_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencia',
            name='aluno_id',
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='disciplina_id',
        ),
        migrations.AddField(
            model_name='frequencia',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Aluno'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='discliplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Disciplina'),
        ),
    ]
