# Generated by Django 2.2.6 on 2019-10-25 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190925_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nota1', models.DecimalField(decimal_places=2, max_digits=9)),
                ('nota2', models.DecimalField(decimal_places=2, max_digits=9)),
                ('nota3', models.DecimalField(decimal_places=2, max_digits=9)),
                ('nota4', models.DecimalField(decimal_places=2, max_digits=9)),
                ('aluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Aluno')),
                ('discliplina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Disciplina')),
            ],
        ),
    ]
