# Generated by Django 2.2.6 on 2019-10-27 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencia',
            name='discliplina',
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.AlunoDisciplina'),
        ),
    ]
