# Generated by Django 2.2.5 on 2019-11-03 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20191101_1017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notas',
        ),
    ]
